# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jolly_rather.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JollyRatherMainWindow(object):
    def setupUi(self, JollyRatherMainWindow):
        JollyRatherMainWindow.setObjectName("JollyRatherMainWindow")
        JollyRatherMainWindow.resize(531, 262)
        self.centralwidget = QtWidgets.QWidget(JollyRatherMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.todo_label = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(16)
        self.todo_label.setFont(font)
        self.todo_label.setObjectName("todo_label")
        self.todo_list = QtWidgets.QPlainTextEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.todo_list.setFont(font)
        self.todo_list.setObjectName("todo_list")
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.option_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.option_splitter.setOrientation(QtCore.Qt.Vertical)
        self.option_splitter.setObjectName("option_splitter")
        self.headline_label = QtWidgets.QLabel(self.option_splitter)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(16)
        self.headline_label.setFont(font)
        self.headline_label.setObjectName("headline_label")
        self.opt1 = QtWidgets.QPushButton(self.option_splitter)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.opt1.setFont(font)
        self.opt1.setObjectName("opt1")
        self.opt2 = QtWidgets.QPushButton(self.option_splitter)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.opt2.setFont(font)
        self.opt2.setObjectName("opt2")
        self.horizontalLayout_3.addWidget(self.option_splitter)
        JollyRatherMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JollyRatherMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        JollyRatherMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JollyRatherMainWindow)
        self.statusbar.setObjectName("statusbar")
        JollyRatherMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(JollyRatherMainWindow)
        QtCore.QMetaObject.connectSlotsByName(JollyRatherMainWindow)

    def retranslateUi(self, JollyRatherMainWindow):
        _translate = QtCore.QCoreApplication.translate
        JollyRatherMainWindow.setWindowTitle(_translate("JollyRatherMainWindow", "Jolly Rather (saves your list when you quit)"))
        self.todo_label.setText(_translate("JollyRatherMainWindow", "Todo List"))
        self.todo_list.setPlainText(_translate("JollyRatherMainWindow", "Fly the parrot\n"
"Swab the deck\n"
"Bury treasure\n"
"Shine peg leg"))
        self.headline_label.setText(_translate("JollyRatherMainWindow", "Would you rather..."))
        self.opt1.setText(_translate("JollyRatherMainWindow", "Option 1"))
        self.opt2.setText(_translate("JollyRatherMainWindow", "Option 2"))
